"use strict";
exports.__esModule = true;
var circle_1 = require("./circle");
var rectangle_1 = require("./rectangle");
var circlOBJ = new circle_1.Circle(2);
circlOBJ.Myarea();
circlOBJ.display();
var rectObj = new rectangle_1.Rectangle(2, 3);
rectObj.Myarea();
rectObj.display();
